### ISSUE TITLE
erreur sur l'utilisation du generateur dans Collector.js:228

### ISSUE THREAD

**Issue by Nine-s** [LeoPenaguin/kaamelott-bot#2]
Merci pour ce tutoriel!
Quand je lance la commande 
`node index.js` 

J'ai obtienu plusieurs erreurs de synthaxes. Celles-ci étaient liées à certaines logiques `try/catch` dans plusieurs fichiers où le catch était vide. Je les ai résolues mais j'ai maintenant une erreur plus difficile à résoudre:

```
/home/ninon/bot/kaamelott-bot/node_modules/discord.js/src/structures/interfaces/Collector.js:228
          yield queue.shift();
          ^^^^^

SyntaxError: Unexpected strict mode reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ninon/bot/kaamelott-bot/node_modules/discord.js/src/structures/MessageCollector.js:3:19)
```

Mon systeme: 

Ubuntu 18.04
```
node --version
v8.10.0
```
```
npm -version
3.5.2
```
```
ffmpeg -version 
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
```

**Comment by Nine-s** [comment]
Les erreures sont résolues grace à l'upgrade de node en utilisant nvm:
https://phoenixnap.com/kb/update-node-js-version
